"""
Cross-tool diff: compare n2v GraphStar reach against MATLAB GNNV reference.

Both tools produce sound over-approximations of the same true reachable set,
so the n2v box should *contain* the MATLAB box (modulo LP solver tolerance).
We report two quantities per (instance, eps) cell:

  1. Containment slack:  matlab_lb - n2v_lb  (and n2v_ub - matlab_ub)
     Negative values indicate n2v is *tighter* than MATLAB on some output,
     which would either be a soundness regression or a known approximation
     gap going the other way; large negatives are a hard failure.

  2. Width-inflation ratio:  width_n2v / width_matlab
     n2v's ReLU approx classifies neurons via the predicate-box estimate
     instead of LP, so it can produce wider bounds; this metric quantifies
     the gap.  We only compute it on outputs where width_matlab is
     above a small floor (default 1e-6) so always-inactive neurons
     (matlab_w == 0) don't pollute the ratio.

Reference data is generated by
examples/GNN/matlab_reference/generate_ieee24_reference.m.

Usage:
    python compare_with_matlab.py
    python compare_with_matlab.py --soundness_tol 1e-7 --inflation_tol 1.5
"""

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List

import numpy as np
from scipy.io import loadmat

from n2v.sets import GraphStar
from n2v.nn.layer_ops.gcn_reach import gcn_stack_reach
from n2v.utils import load_gnn_mat


DEFAULT_REFERENCE = (
    Path(__file__).parent / "matlab_reference" / "ieee24_pf_reference.mat"
)


@dataclass
class CellResult:
    instance: int
    eps: float
    matlab_width_mean: float
    matlab_width_max: float
    n2v_width_mean: float
    n2v_width_max: float
    soundness_slack: float    # min(matlab_lb - n2v_lb, n2v_ub - matlab_ub); >= 0 means n2v contains matlab
    width_ratio_mean: float
    width_ratio_max: float
    matlab_time_sec: float


def _decode_str(arr) -> str:
    return str(np.asarray(arr).flatten()[0])


def _load_reference(path: Path) -> dict:
    raw = loadmat(str(path))
    return {
        "checkpoint": _decode_str(raw["checkpoint"]),
        "instances": np.asarray(raw["instances"]).flatten().astype(int),
        "eps_values": np.asarray(raw["eps_values"]).flatten().astype(float),
        "lp_solver": _decode_str(raw["lp_solver"]),
        "lb": raw["lb"],
        "ub": raw["ub"],
        "center": raw["center"],
        "times_sec": np.asarray(raw["times_sec"], dtype=float),
        "matlab_version": _decode_str(raw["matlab_version"]),
        "nnv_method": _decode_str(raw["nnv_method"]),
        "generated_at": _decode_str(raw["generated_at"]),
    }


def compare(
    reference_path: Path,
    soundness_tol: float = 1e-7,
    inflation_tol: float = 1.5,
    width_floor: float = 1e-6,
) -> List[CellResult]:
    ref = _load_reference(reference_path)
    print(f"reference: {reference_path}")
    print(f"  generated: {ref['generated_at']}  matlab: {ref['matlab_version']}")
    print(f"  method: {ref['nnv_method']}  lp_solver: {ref['lp_solver']}")
    print(f"  cells: {len(ref['instances'])} instances x {len(ref['eps_values'])} eps")

    model = load_gnn_mat(ref["checkpoint"])
    instances = ref["instances"]
    eps_values = ref["eps_values"]

    print()
    print("inst   eps      matlab_s   matlab_w_mean   n2v_w_mean   sound_slack   "
          "infl_mean  infl_max")
    print("-" * 100)

    cells: List[CellResult] = []
    for ii, inst_idx in enumerate(instances):
        # MATLAB indices are 1-based; X_test list is 0-based.
        X = model.X_test[int(inst_idx) - 1]
        for jj, eps in enumerate(eps_values):
            gs_in = GraphStar.from_bounds(
                X - float(eps), X + float(eps), adjacency=model.A_norm
            )
            outs = gcn_stack_reach(gs_in, model.gcn_layers, has_relu=model.has_relu)
            assert len(outs) == 1
            lb_n2v, ub_n2v = outs[0].get_ranges()

            lb_mat = np.asarray(ref["lb"][ii, jj], dtype=float)
            ub_mat = np.asarray(ref["ub"][ii, jj], dtype=float)
            assert lb_mat.shape == lb_n2v.shape, (
                f"shape mismatch instance {inst_idx} eps {eps}: "
                f"matlab {lb_mat.shape} vs n2v {lb_n2v.shape}"
            )

            # Containment slack: positive means n2v's box contains matlab's box.
            slack_lb = lb_mat - lb_n2v
            slack_ub = ub_n2v - ub_mat
            sound_slack = float(min(slack_lb.min(), slack_ub.min()))

            width_mat = ub_mat - lb_mat
            width_n2v = ub_n2v - lb_n2v

            mask = width_mat > width_floor
            if mask.any():
                ratio = width_n2v[mask] / width_mat[mask]
                ratio_mean = float(ratio.mean())
                ratio_max = float(ratio.max())
            else:
                ratio_mean = 1.0
                ratio_max = 1.0

            cells.append(
                CellResult(
                    instance=int(inst_idx),
                    eps=float(eps),
                    matlab_width_mean=float(width_mat.mean()),
                    matlab_width_max=float(width_mat.max()),
                    n2v_width_mean=float(width_n2v.mean()),
                    n2v_width_max=float(width_n2v.max()),
                    soundness_slack=sound_slack,
                    width_ratio_mean=ratio_mean,
                    width_ratio_max=ratio_max,
                    matlab_time_sec=float(ref["times_sec"][ii, jj]),
                )
            )

            print(f"  {int(inst_idx):3d}  {float(eps):7.1e}  "
                  f"{float(ref['times_sec'][ii, jj]):7.2f}    "
                  f"{float(width_mat.mean()):.3e}    "
                  f"{float(width_n2v.mean()):.3e}    "
                  f"{sound_slack:+.2e}     "
                  f"{ratio_mean:6.3f}     {ratio_max:6.3f}")

    print("-" * 100)
    worst_slack = min(c.soundness_slack for c in cells) if cells else 0.0
    worst_infl = max(c.width_ratio_max for c in cells) if cells else 1.0
    print(f"worst soundness slack: {worst_slack:+.3e}  (tol -{soundness_tol:.1e})")
    print(f"worst width inflation: {worst_infl:.3f}     (tol  {inflation_tol:.2f})")

    failed = []
    if worst_slack < -soundness_tol:
        failed.append("soundness")
    if worst_infl > inflation_tol:
        failed.append("inflation")
    if failed:
        print(f"FAIL: {', '.join(failed)} threshold(s) exceeded", file=sys.stderr)
    else:
        print("OK: n2v contains MATLAB within tolerance")
    return cells


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", type=Path, default=DEFAULT_REFERENCE)
    parser.add_argument(
        "--soundness_tol",
        type=float,
        default=1e-7,
        help="Allowed negative slack from LP solver tolerance. n2v's box must contain "
             "MATLAB's box up to this slack on each side.",
    )
    parser.add_argument(
        "--inflation_tol",
        type=float,
        default=25.0,
        help="Maximum allowed width_n2v / width_matlab on any single output, computed "
             "only over outputs where matlab width > 1e-6.  The default is loose "
             "because n2v's approx-star ReLU classifies neurons via the predicate-box "
             "estimate while MATLAB uses LP, so n2v widens at large eps.  Soundness "
             "(n2v contains MATLAB) is the hard correctness property; this is "
             "a tightness regression guard.",
    )
    args = parser.parse_args()

    if not args.reference.exists():
        print(
            f"reference not found: {args.reference}\n"
            "Run examples/GNN/matlab_reference/generate_ieee24_reference.m first.",
            file=sys.stderr,
        )
        return 1

    cells = compare(
        args.reference,
        soundness_tol=args.soundness_tol,
        inflation_tol=args.inflation_tol,
    )
    worst_slack = min(c.soundness_slack for c in cells) if cells else 0.0
    worst_infl = max(c.width_ratio_max for c in cells) if cells else 1.0
    if worst_slack < -args.soundness_tol or worst_infl > args.inflation_tol:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
